apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: storage-ms
  name: storage-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storage-ms
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: storage-ms
    spec:
      containers:
      - image: decioc/storage-ms
        name: storage-ms
        resources:
          requests:
            cpu: 200m
            memory: 600Mi
          limits:
            cpu: 200m
            memory: 800Mi
---
apiVersion: v1
kind: Service
metadata:
  name: storage-ms
  labels:
    app: storage-ms
spec:
  type: ClusterIP
  ports:
    - name: storage-ms
      port: 8083
      protocol: TCP
  selector:
    app: storage-ms
status: {}
